// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaCitas.Entities.Entities;

public partial class Clientes
{
    [NotMapped]
    public string Usua_Nombre { get; set; }

    [NotMapped]
    public string Usua_Contraseña { get; set; }

    public int Clie_Id { get; set; }

    public string Clie_Dni { get; set; }

    public string Clie_Nombre { get; set; }

    public string Clie_Apellido { get; set; }

    public string Clie_Sexo { get; set; }

    public DateTime? Clie_FechaNacimiento { get; set; }

    public virtual ICollection<Citas> Citas { get; set; } = new List<Citas>();

    public virtual ICollection<Usuarios> Usuarios { get; set; } = new List<Usuarios>();
}