// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaCitas.Entities.Entities;

public partial class Especialidades
{
    public int Espe_Id { get; set; }

    public string Espe_Nombre { get; set; }

    public virtual ICollection<Citas> Citas { get; set; } = new List<Citas>();
}