// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaCitas.Entities.Entities;

public partial class Usuarios
{
    public int Usua_Id { get; set; }

    public string Usua_Nombre { get; set; }

    public string Usua_Contraseña { get; set; }

    public int? Clie_Id { get; set; }

    public virtual Clientes Clie { get; set; }
}